CREATE DATABASE QLSINHVIEN

USE QLSINHVIEN

GO
CREATE TABLE KHOA
(
	MAKHOA CHAR(4) CONSTRAINT K_MAKHOA_PK PRIMARY KEY,
	TENKHOA NVARCHAR(20) CONSTRAINT K_TENKHOA_UQ UNIQUE
)

GO
CREATE TABLE LOP
(
	MALOP CHAR(4) CONSTRAINT L_MALOP_PK PRIMARY KEY,
	TENLOP NVARCHAR(20) CONSTRAINT L_TENLOP_UQ UNIQUE,
	MAKHOA CHAR(4) CONSTRAINT L_MAKHOA_FK FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA) 
)

GO
CREATE TABLE SINHVIEN
(
	MASV CHAR(3) CONSTRAINT SV_MASV_PK PRIMARY KEY,
	HOTEN NVARCHAR(40) NOT NULL,
	NGAYSINH DATETIME,
	MALOP CHAR(4) CONSTRAINT SV_MALOP_FK FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
)

GO
CREATE TABLE MONHOC
(
	MAMH CHAR(4) CONSTRAINT MH_MAMH_PK PRIMARY KEY,
	TENMH NVARCHAR(30) CONSTRAINT MH_TENMH_UQ UNIQUE
)

GO
CREATE TABLE DIEM
(
	MASV CHAR(3) NOT NULL,
	MAMH  CHAR(4) NOT NULL,
	DIEM DECIMAL(4,2),
	CONSTRAINT D_MASV_MAMH_PK PRIMARY KEY (MASV, MAMH),
	CONSTRAINT D_MASV_FK FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
	CONSTRAINT D_MAMH_FK FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
)

SELECT SINHVIEN.MASV, SINHVIEN.HOTEN, SINHVIEN.NGAYSINH, DIEM.DIEM, MONHOC.MAMH, MONHOC.TENMH
FROM SINHVIEN, MONHOC, DIEM
WHERE SINHVIEN.MASV = DIEM.MASV AND DIEM.MAMH = MONHOC.MAMH


SELECT KHOA.MAKHOA FROM LOP, KHOA, SINHVIEN
WHERE KHOA.MAKHOA = LOP.MAKHOA AND SINHVIEN.MALOP = LOP.MALOP

SELECT SINHVIEN.* FROM SINHVIEN,LOP
WHERE SINHVIEN.MALOP = LOP.MALOP

SELECT LOP.MALOP FROM LOP, KHOA
WHERE LOP.MAKHOA = KHOA.MAKHOA	AND KHOA.TENKHOA = N'Công nghệ thông tin'

SELECT SINHVIEN.MASV, SINHVIEN.HOTEN, SINHVIEN.NGAYSINH, DIEM.DIEM, MONHOC.MAMH, MONHOC.TENMH 
FROM SINHVIEN, MONHOC, DIEM, LOP
WHERE SINHVIEN.MASV = DIEM.MASV AND DIEM.MAMH = MONHOC.MAMH AND LOP.MALOP = SINHVIEN.MALOP AND LOP.TENLOP = 'Hóa 1'

DROP TABLE DIEM;
DROP TABLE KHOA;
DROP TABLE LOP;
DROP TABLE MONHOC;
DROP TABLE SINHVIEN

SELECT SINHVIEN.MASV, SINHVIEN.HOTEN, SINHVIEN.NGAYSINH, LOP.TENLOP
FROM SINHVIEN, LOP 
WHERE SINHVIEN.MALOP = LOP.MALOP AND LOP.TENLOP LIKE 'CNTTA'

SELECT L.MAKHOA
FROM SINHVIEN AS SV, LOP AS L
WHERE SV.MALOP = L.MALOP

SELECT MALOP FROM LOP WHERE TENLOP LIKE 'CNTTA'